services:
  cs_server:
    image: cs_dev_webserver
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile
      target: es_webserver
    volumes:
      - ./../..:/var/www
    environment:
      RUN_USER: "${UID}:${GID}"
      APP_MYSQL_HOST: cs_database
      APP_MYSQL_USER: crittersystem
      APP_MYSQL_PASSWORD: crittersystem
      APP_MYSQL_DATABASE: crittersystem
      PHP_IDE_CONFIG: serverName=crittersystem
      ENVIRONMENT: development
      MAIL_DRIVER: log
      APP_NAME: Crittersystem DEV
    env_file: deployment.env
    ports:
      - "127.0.0.1:5080:80"
    depends_on:
      - cs_database
  cs_workspace:
    image: cs_dev_workspace
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile
      target: es_workspace
    user: "${UID}:${GID}"
    volumes:
      - ./../..:/var/www
    environment:
      HOME: /tmp
      MYSQL_HOST: cs_database
      MYSQL_USER: crittersystem
      MYSQL_PASSWORD: crittersystem
      MYSQL_DATABASE: crittersystem
      ENVIRONMENT: development
      MAIL_DRIVER: log
      APP_NAME: Crittersystem DEV
    depends_on:
      - cs_database
  cs_phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: cs_database
    ports:
      - "127.0.0.1:8888:80"
    depends_on:
      - cs_database
    profiles: [ dev ]
  cs_database:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: crittersystem
      MYSQL_USER: crittersystem
      MYSQL_PASSWORD: crittersystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: {}
